fastq_dir: "fastqs" # This directory has all files together (no subdirectories) all uncompressed and with .fasta extension
sample_file: read_pair_table.csv
sample_reference_file: sample_reference.csv
lineage_reference_file: lineage_references.csv
reference_directory: "references/" #This directory name must end with the "/"
reference_fasta: "FungiDB-65_CneoformansH99_Genome.fasta"
reference_gff: "FungiDB-65_CneoformansH99.gff"
threads_snippy: 4
threads_liftoff: 4
threads_mosdepth: 4
mosdepth_window: 500
mosdepth_min_mapq: 1
loci: "-g results/MAT.txt -g results/centromeres.txt -g results/rRNA.txt"
locitsv: "results/loci_interest.tsv"