fastq_dir: "fastqs" # This directory has all files together (no subdirectories) all uncompressed and with .fasta extension (use double quotes and no slash)
sample_file: "files/read_pair_table.csv" # CSV table with columns sample,run,file1,file2,size (no quotes)
sample_reference_file: "files/sample_reference.csv" # CSV table with columns lineage,sample,file1,file2,refgenome (no quotes)
lineage_reference_file: "files/lineage_references.csv" # CSV table with columns group,strain,genbank,file (no quotes)
reference_directory: "references/" # Directory name for the references (must end with the "/" and use double quotes)
reference_fasta: "FungiDB-65_CneoformansH99_Genome.fasta" # (double quotes)
reference_gff: "FungiDB-65_CneoformansH99.gff" # (double quotes)
threads_snippy: 4
threads_liftoff: 4
threads_mosdepth: 4
mosdepth_window: 500
mosdepth_min_mapq: 20
loci: "-g files/MAT.txt -g files/centromeres.txt -g files/rRNA.txt -g files/TOR.txt"
locitsv: "files/loci_interest.tsv"
