# =================================================================================================
#   Choose which workflow to run
# =================================================================================================

workflow: "analysis" # Options: "analysis", "join_datasets"

# =================================================================================================
# Sample workflow parameters
# =================================================================================================
# ------------------Input--------------------------------------------------------------------------

fastqs:
  directory: "data/samples" # Relative path to directory with all FASTQ files 
  fastq_suffix1: "_1.fq.gz" # Everything after the sample name of the forward reads file.
  fastq_suffix2: "_2.fq.gz" # Everything after the sample name of the reverse reads file.

references: 
  directory: "data/references/" # Path to directory with reference genomes.

samples: "config/sample_metadata.csv" # Relative path to metadata CSV table.
chromosomes: "config/chromosome_names.csv" # Relative path to chromosome names CSV table.
species_name: "Cryptococcus_neoformans" 
samples_to_exclude: # Optional: File with list of samples to exclude from all analyses.
# ------------------Output-------------------------------------------------------------------------

output_directory: "results_2024-10-05" # Name for the output directory

# ------------------Annotation of reference genomes------------------------------------------------

annotate_references:
  activate: True
  directory: "data/main_reference" # Relative path to directory with main reference files.
  fasta: "FungiDB-65_CneoformansH99_Genome.fasta" # Main reference fasta.
  gff: "FungiDB-65_CneoformansH99.gff" # Main reference GFF. 
  liftoff:
    threads: 12
    extra: ""

# ------------------Depth and quality analyses-----------------------------------------------------
depth_quality: 
  mosdepth: 
    threads: 12  
    window: 500 # Window size for mosdepth
    min_mapq: 20 # Minimum mapping quality for mosdepth
    extra: ""
  flag_quality: # Minimum values for a sample to be considered to have a good quality read mapping
    low_MAPQ_limit: 20 # Top limit for low MAPQ reads
    high_MAPQ_limit: 60 # Bottom limit for high MAPQ reads
    min_position_depth: 5 # Minimum depth for a position to be considered covered
    min_percent_MAPQ: 75 # Minimum percentage of reads in the high MAPQ bin
    min_percent_genome-wide_depth: 2 # Minimum percentage of genome-wide depth (Global mode)
    min_percent_properly_paired_reads: 25 # Minimum percentage of properly paired mapped reads
    min_percent_coverage: 50 # Minimum percentage of genome-wide coverage
    exclude_samples: True # Exclude samples that do not meet the quality thresholds

# ------------------Copy-number variant calling----------------------------------------------------
cnv:
  activate: True
  smoothing_size: 15 # Parameter for median filtering smoothing of the coverage
  depth_threshold: 0.6 # Minimum change in coverage for cnv calling
  repeats:
    repeats_database: "config/RepBase.fasta"
    repeats_threads: 20
    repeats_fraction: 0.5 # Fraction of repetitive bases allowed for calculating global depth

# ------------------MAPQ and Depth of genetic features---------------------------------------------
genes_mapq_depth:
  activate: True

# ------------------Variant annotation-------------------------------------------------------------
snpeff:
  activate: True
  extra: ""

# ------------------Plotting-----------------------------------------------------------------------
plotting: 
  activate: True
  loci: "config/loci.csv" # Relative path to table with loci to add to plots
  metadata2color : "source" # Column name in the samples table to color the samples in the plots
  scale : 0.7 # Ggsave scale parameter to adjust the size of the dataset plots. Use lower values for fewer samples and bigger values for more samples.

# ------------------Database-----------------------------------------------------------------------
database:
  activate: True

# =================================================================================================
# Join datasets workflow parameters
# =================================================================================================
# This workflow joins the results of running the sample_workflow in different datasets. It assumes that
# if the same lineage is present in the different datasets, the same reference genome was used.
# datasets_paths: "results_1,results_2"
# datasets_names: "R1,R2"
# joint_output_directory: "results_joined_R1R2"
datasets_paths: "/FastData/czirion/Crypto_Desjardins/results_2024-10-04,/FastData/czirion/ashton/results_2024-10-05" # Comma-separated list of directories with datasets to join.
datasets_names: "Desjardins,Ashton" # Comma-separated list of names for the datasets.
joint_output_directory: "results_joined" # Name for the output directory with joined datasets.

# =================================================================================================
#   Parameters for individual tools
# =================================================================================================

snippy:
  threads: 12
  extra: ""

liftoff:
  threads: 12
  extra: ""

agat:
  extra: ""

